config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tags, param: :tag_id, only: [:index, :show]
  resources :users, only: [:show]
  resources :prototypes do
    scope module: :prototypes do
      resources :likes, only:[:create, :destroy]
      resources :comments, only:[:create]
    end
    collection do
      get :popular
    end
  end
  resources :memos, only: [:index, :create, :destroy]
  root to: "prototypes#index"
end

app/models/captured_image.rb
class CapturedImage < ActiveRecord::Base
  enum role: [:main, :sub]
  mount_uploader :name, ImageUploader
  belongs_to :prototype
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :prototype, counter_cache: true

  validates :text, presence: true

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :prototype, counter_cache: true
end

app/models/memo.rb
class Memo < ActiveRecord::Base
	enum status: [:need, :leftover]
	validates_presence_of :text
	belongs_to :user
end

app/models/prototype.rb
class Prototype < ActiveRecord::Base

  validates_presence_of :user_id, :title, :time, :cost

  belongs_to :user
  has_many :captured_images
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  accepts_nested_attributes_for :captured_images

  paginates_per 8

  acts_as_taggable

  def main_image
    captured_images.main.first.name
  end

  def sub_images
    captured_images.sub.map(&:name)
  end

  def posted_date
    created_at.strftime('%b %d')
  end

  def create_captured_images(captured_image)
    captured_image.each{ |k, v| k == 'main' ? captured_images.main.create(name: v) : captured_images.sub.create(name: v) }
  end

  def update_captured_images(captured_image)
    captured_image.each do |k, v|
     k == '0' ? captured_images.main.first.update(name: v[:name]) : captured_images.sub[k.to_i - 1].update(name: v[:name])
    end
  end

  def whether_user_liked(user)
    likes.find_by(user_id: user)
  end



end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader

  has_many :prototypes
  has_many :likes
  has_many :comments
  has_many :memos

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  add_flash_types :success, :info, :warning, :danger

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:name, :avatar)
    devise_parameter_sanitizer.for(:account_update).push(:name, :avatar)
  end

end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
before_action :authenticate_user!

def index
	@memos = current_user.memos
	@memo = Memo.new
end

def create
	Memo.create(memo_params)
	@memos = current_user.memos
end

def destroy
	Memo.find(params[:id]).destroy
	@memos = current_user.memos
end

private
def memo_params
	params.require(:memo).permit(:text, :status).merge(user_id: current_user.id)
end

end

app/controllers/prototypes/comments_controller.rb
class Prototypes::CommentsController < ApplicationController
  def create
    @prototype = Prototype.find(params[:prototype_id])
    @prototype.comments.create(comment_params)
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id)
  end

end

app/controllers/prototypes/likes_controller.rb
class Prototypes::LikesController < ApplicationController
  def create
    @like = current_user.likes.create(prototype_id: params[:prototype_id])
    @prototype = Prototype.find(params[:prototype_id])
  end

  def destroy
    Like.find_by(user_id: current_user.id, prototype_id: params[:prototype_id]).destroy
    @prototype = Prototype.find(params[:prototype_id])
  end
end

app/controllers/prototypes/newest_controller.rb
class Prototypes::NewestController < ApplicationController
  def index
    @prototypes = Prototype.order('created_at DESC').page(params[:page])
  end
end

app/controllers/prototypes/popular_controller.rb
class Prototypes::PopularController < ApplicationController
  def index
    @prototypes = Prototype.order('likes_count DESC').page(params[:page])
  end
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController

  before_action :set_prototype, only: [:show, :edit, :update]

  def index
    @prototypes = Prototype.order(cost: :ASC).page(params[:page])
  end

  def popular
    @prototypes = Prototype.order(time: :ASC).page(params[:page])
  end

  def new
    @prototype = Prototype.new
    @prototype.captured_images.build
  end

  def create
    @prototype = Prototype.create(prototype_params)
    if @prototype.save
      @prototype.create_captured_images(images_params)
      redirect_to :root, success: 'well done! its time to eat!'
    else
      redirect_to :back, success: 'please fill out all of the required sections'
    end
  end

  def edit
    @captured_images = @prototype.captured_images
  end

  def show
    @like = Like.where(prototype_id: params[:id]).first_or_initialize
    @comment = Comment.new
  end

  def update
    @prototype.update(prototype_params)
    @prototype.update_captured_images(update_images_params)
    redirect_to :root, success: '更新しました'
  end

  def destroy
    @prototype = Prototype.find(params[:id])
    @prototype.destroy
    redirect_to :root, success: '削除しました'
  end

  private
  def prototype_params
    params.require(:prototype).permit(:cost, :time, :title, :url).merge(user_id: current_user.id, tag_list: params[:prototype][:tags].values)
  end

  def images_params
    params.require(:prototype).require(:captured_images_attributes).require('0')
  end

  def update_images_params
    params.require(:prototype).require(:captured_images_attributes)
  end

  def set_prototype
    @prototype = Prototype.find(params[:id])
  end

def tags_params
  params.require(:prototype).require(:tags).values
end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
	@tags = ActsAsTaggableOn::Tag.order('name ASC')
  end

  def show
    @prototypes = Prototype.tagged_with(params[:tag_name]).page(params[:page])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    user = User.find(params[:id])
    if user.id == current_user.id
      user.update(user_params)
      redirect_to root_path
    end
  end

  def show
    @prototypes = current_user.prototypes.page(params[:page])
  end


  private
  def user_params
    params.require(:user).permit(:name, :email, :image)
  end
end

app/views/layouts/_footer.html.haml
.container
  %footer
    %p &copy; it was tasty 2015.

app/views/layouts/_header.html.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    %button.navbar-toggle{ type: "button", data:{ toggle: "collapse", target: ".navbar-responsive-collapse" } }
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    = link_to (image_tag "logo9.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "65px"), root_path, class: "navbar-brand"
    .navbar-collapse.collapse.navbar-responsive-collapse
      - if user_signed_in?
        //login
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            %a.dropdown-toggle{ aria: { expanded: false }, data: { toggle: "dropdown" }, href: '#', role: "button" }
              = current_user.name
              %span.caret
            %ul.dropdown-menu{ role: "menu" }
              %li
                = link_to "My page",user_path(current_user)

              %li
                = link_to "Profile Edit", edit_user_registration_path
              %li
                = link_to "Logout", destroy_user_session_path, method: :delete
          %li
            .btn.btn-primary.navbar-btn
              = link_to "New Dish", new_prototype_path
      - else
        //not login
        %ul.nav.navbar-nav.navbar-right
          %li
            .btn.btn-primary.navbar-btn
              = link_to "Get Started", new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: "text/html; charset=UTF-8", http:{ equiv: "Content-Type" } }/
    %title Protospace
    = stylesheet_link_tag    'application', media: 'all', data:{ turbolinks:{ track: true } }
    = javascript_include_tag 'application', data:{ turbolinks:{ track: true } }
    = csrf_meta_tags
  %body
    = render "layouts/header"
    - flash.each do |key, value|
      %div{ class: "alert alert-#{key}" }
        "#{value}"
        %button{ class: 'close', data:{ dismiss: 'alert'}, aria:{ hidden: 'true' } } &times;
    = yield
    = render "layouts/footer"

app/views/login/index.html.haml
.container
  %form.form-signin
    %h2.form-signin-heading Please sign in
    %label.sr-only{ for: "inputEmail" } Email address
    %input#inputEmail.form-control{ autofocus: "", placeholder: "Email address", required: "", type: "email" }/
    %label.sr-only{ for: "inputPassword" } Password
    %input#inputPassword.form-control{ placeholder: "Password", required: "", type: "password" }/
    .checkbox
      %label
        %input{ type: "checkbox", value: "remember-me" }/
        Remember me
    %button.btn.btn-lg.btn-primary.btn-block{ type: "submit" } Sign in
  .text-center
    %p 
      Not a member?
      = link_to "Sign up now", "user/new"

app/views/memos/_memo.html.haml
- if memo.need?
  .memo-contain
    %li.list-group-item.list-group-item-item-info.memo-list.memo-buy
      = memo.text
      = link_to 'buy', memo_path(memo), method: :delete, remote: true
- if memo.leftover?
  .memo-contain
    %li.list-group-item.list-group-item-item-info.memo-list.memo-eat
      = memo.text
      = link_to 'eat', memo_path(memo), method: :delete, remote: true

app/views/memos/create.js.erb
$("#memo_text").val("");
$("#left-text").val("");
$("ul.list-group").html("<%= j(render @memos) %>");

app/views/memos/destroy.js.erb
$("ul.list-group").html("<%= j(render @memos) %>")

app/views/memos/index.html.haml
.container.user-page
  %header.user-nav
    .media
      .container.proto-new
        = form_for @memo, remote: true do |f|
          .row.proto-description
            .col-md-12
              = f.text_field :text
              = f.hidden_field :status, value: :need
          .row.text-center.proto-btn
            = f.submit 'need', class: 'btn btn-primary btn-block'
      .container.proto-new
        = form_for @memo, remote: true do |f|
          .row.proto-description
            .col-md-12
              = f.text_field :text, id: 'left-text'
              = f.hidden_field :status, value: :leftover
          .row.text-center.proto-btn
            = f.submit 'left', class: 'btn btn-primary btn-block'
      %ul.list-group.memo-float
        = render @memos

app/views/prototypes/_prototype.html.haml
.container.proto-list
  .row
    - @prototypes.each do |prototype|
      - unless prototype.captured_images.main.blank?
        .col-sm-4.col-md-3.proto-content
          .thumbnail
            = link_to prototype_path(prototype) do
              = image_tag prototype.captured_images.main[0].name
              .caption
                %h3
                  = link_to prototype.title, prototype_path(prototype)
                .proto-meta
                  .proto-user
                    = link_to prototype.user.name, root_path
                  .proto-posted
                    = prototype.posted_date
                %ul.proto-tag-list.list-inline
                  - unless prototype.tag_list.blank?
                    - prototype.tags.each do |tag|
                      %li 
                        = link_to tag.name, tag_path(tag, tag_name: tag.name), class: 'btn btn-default'
.text-center
  = paginate @prototypes, remote: true

app/views/prototypes/comments/_comment.html.haml
.media
  .media-left
    = link_to '#' do
      = image_tag comment.user.avatar, width: 64, height: 64
  .media-body
    %h4#top-aligned-media.media-heading
      = comment.user.name
      %a.anchorjs-link{ href: '#top-aligned-media'}
        %span.anchorjs-icon
    %p
      = comment.text

app/views/prototypes/comments/create.js.erb
$('#comment_field').val('');
$('#comment_count').text(
  '<%= j(" (#{@prototype.comments_count}) ") %>'
);
$('#comments').html(
  '<%= j(render partial: 'prototypes/comments/comment', collection: @prototype.comments) %>'
  );

app/views/prototypes/edit.html.haml
.container.proto-new
  = form_for @prototype do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          = f.text_field :title, placeholder: 'Title', class: 'proto-new-title'
        .row
          .col-md-12
            .cover-image-upload
              = f.fields_for :captured_images, @captured_images.main do |image|
                = image_tag (), { id: 'main_image_preview', class: 'col-md-12' }
                = image.file_field :name
                = image.hidden_field :status, value: 'main'
          .col-md-12
            %ul.proto-sub-list.list-group
              - @captured_images.sub.each do |sub|
                %li.list-group-item.col-md-4
                  .image-upload
                    = f.fields_for :captured_images, sub do |image|
                      =image.file_field :name
                      =image.hidden_field :status, value: 'sub'
        .row.proto-description
          .col-md-12
            = f.text_field :cost, placeholder: 'how much did it cost'
          .col-md-12
            = f.text_field :time, placeholder: 'how long did it take?'
        = f.fields_for :tags do |tag|
          .col-md-12
            %h4 Tag List
            .row
              .col-md-3
                = tag.text_field :'0'
              .col-md-3
                = tag.text_field :'1'
              .col-md-3
                = tag.text_field :'2'
        .row.text-center.proto-btn
          = f.submit 'PUBLISH', class: 'btn btn-lg btn-primary btn-block'

app/views/prototypes/index.html.haml
.jumbotron
  .container.text-center
    = image_tag 'tasty2.png', alt: 'PROTO TYPE - SHARE THE PROTOTYPE', height: '130x1z1px'

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li{ role: 'presentation' }
          = link_to 'time', popular_prototypes_path, remote: true, class: 'popular'
        %li{ role: 'presentation' }
          = link_to 'cost', prototypes_path, remote: true, class: 'newest btn-primary'
        %li{ role: 'presentation' }
          = link_to 'material', tags_path, class: 'btn btn-material col-lg-1'
        %li{ role: 'presentation' }
          = link_to "memo", memos_path, class: 'btn btn-memo col-lg-1'
.proto-contents
  = render partial: 'prototypes/prototype'

app/views/prototypes/index.js.erb
$('a').removeClass('btn-primary');
$('a.newest').addClass('btn-primary');
$('.proto-contents').html(
  '<%= j(render partial: 'prototypes/prototype') %>'
);

app/views/prototypes/likes/_like.html.haml
- if user_signed_in? && @prototype.whether_user_liked(current_user)
  = link_to prototype_like_path(@like, prototype_id: @prototype.id), method: :delete, id: 'like-button', remote: true do
    = button_tag(class: 'btn btn-default') do
      = image_tag 'icon_heart_red.svg'
      %span.num
        Like
        = @prototype.likes_count

- elsif user_signed_in?
  = link_to prototype_likes_path(@prototype), method: :post, id: 'like-button', remote: true do
    = button_tag(class: 'btn btn-default') do
      = image_tag 'icon_heart.svg'
      %span.num
        Like
        = @prototype.likes_count

app/views/prototypes/likes/create.js.erb
$('#like-button').html(
  "<%= j(render 'prototypes/likes/like') %>"
);

app/views/prototypes/likes/destroy.js.erb
$('#like-button').html(
  "<%= j(render 'prototypes/likes/like') %>"
);

app/views/prototypes/new.html.haml
.container.proto-new
  = form_for @prototype do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          = f.text_field :title, placeholder: 'what did you cook?', class: 'proto-new-title'
      = f.fields_for :captured_images do |image|
        .row
          .col-md-12
            .cover-image-upload
              = image_tag (), { id: 'main_image_preview', class: 'col-md-12' }
              = image.file_field :main, required: true
          .col-md-12
            %ul.proto-sub-list.list-group
              - 1.upto(3) do |i|
                %li.list-group-item.col-md-4
                  .image-upload
                    = image_tag (), id: "sub_#{i}"
                    = image.file_field :"sub#{i}"
              %li.list-group-item.col-md-4#hide_form
                .image-upload
                  = image_tag (), { id: 'sub_4'}
                  = image.file_field :sub4
              %li.list-group-item.col-md-4#add_new_form
                .image-upload-plus
                  %span +
        .row.proto-description
          .col-md-12
            = f.text_field :cost, placeholder: 'how much did it cost?'
          .col-md-12
            = f.text_field :time, placeholder: 'how long did it take?'
          .col-md-12
            = f.text_field :url, placeholder: 'URL for the recipe'
        = f.fields_for :tags do |tag|
          .col-md-12
            %h4 Material
            .row
              .col-md-3
                = tag.text_field :'0'
              .col-md-3
                = tag.text_field :'1'
              .col-md-3
                = tag.text_field :'2'
        .row.text-center.proto-btn
          = f.submit 'eat!!', class: 'btn btn-primary btn-block'

app/views/prototypes/popular.js.erb
$('a').removeClass('btn-primary');
$('a.popular').addClass('btn-primary');
$('.proto-contents').html(
  '<%= j(render partial: 'prototypes/prototype') %>'
);

app/views/prototypes/popular/index.js.erb
$('li').removeClass('active');
$('li.popular').addClass('active');
$('.proto-list .row').html(
  '<%= j(render partial: 'prototypes/prototype', collection: @prototypes) %>'
);

app/views/prototypes/show.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          = link_to image_tag(@prototype.user.avatar, alt: '64x64', data:{ holder:{ rendered: 'true' } }, data:{ src: 'holder.js/64x64' }, style: 'width: 64px; height: 64px;'), root_path, class: 'media-object'
        .media-body
          %h4#top-aligned-media.media-heading
            - if user_signed_in? && current_user.id == @prototype.user.id
              = link_to 'edit', edit_prototype_path(@prototype)
              = link_to 'destroy', prototype_path(@prototype), method: :delete

          .proto-user
            = link_to @prototype.user.name, root_path
    .col-md-6.text-right
      = render 'prototypes/likes/like'
  .row
    .col-md-9
      = image_tag @prototype.main_image, class: 'img-responsive'
    .col-md-3
      %ul.proto-sub-list.list-group
        - @prototype.sub_images.each do |image|
          %li.list-group-item
            = image_tag image, class: 'img-responsive'
  .row.proto-description
    .col-md-3
      %h4 Time
      %p #{ @prototype.time } minutes
    .col-md-6
      %h4 Cost
      %p  ¥ #{ @prototype.cost }
    - unless @prototype.tag_list.blank?
      .col-md-3
        %h4 Tag List
        %ul.proto-tag-list.list-inline
          - @prototype.tags.each do |tag|
            %li 
              = link_to tag.name, tag_path(tag), class: 'btn btn-default'
    .form-group.col-md-2
      = link_to 'link', @prototype.url, class: 'btn btn-primary'
  .row.proto-comments
    %h4.col-md-12
      Comments
      %span.num#comment_count
        = "(#{ @prototype.comments_count })"
      .col-md-8#comments
        = render partial: 'prototypes/comments/comment', collection: @prototype.comments
      %form.form-inline{ role: 'form'}
      - if user_signed_in?
        = form_for @comment, url: prototype_comments_path(@prototype),remote: true do |f|
          %h4 Write a comment
          .row
            .form-group.col-md-10
              = f.text_area :text, placeholder: 'Your commments', rows: '3', class: 'form-control', id: 'comment_field'
            .form-group.col-md-2
              = button_tag 'Comment', class: 'btn btn-primary'

app/views/tags/index.html.haml
.container.tag-container
  .row
    - @tags.each do |tag|
      - if tag.taggings_count > 0
        .tag-list
          .col-sm-4
            = link_to tag.name, tag_path(tag, tag_name: tag.name), class: "btn tag-btn"

app/views/tags/show.html.haml
.container.proto-list
  .row
    = render partial: 'prototypes/prototype'

app/views/users/edit.html.haml
.container.user-new
  = form_for current_user do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h2 Edit Profile
          .user-name_image.row
            .user-name.col-md-10
              = f.text_field :name
            .user-image.col-md-2{ style: 'background-image url(@user.image);' }
              %button.btn.btn-primary Change image
              = f.file_field :image
          = f.text_field :email, class: "user-email"
      .row.text-center.user-btn
        %button.btn.btn-lg.btn-primary.btn-block{ type: "submit" } Save

app/views/users/index.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-left
        %a{ href: "#" }
          %img.media-object{ alt: "64x64", "data-holder-rendered": "true", "data-src": "holder.js/64x64", src: "dataimage/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+PGRlZnMvPjxyZWN0IHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjEzLjQ2MDkzNzUiIHk9IjMyIiBzdHlsZT0iZmlsbDojQUFBQUFBO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQ7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+NjR4NjQ8L3RleHQ+PC9nPjwvc3ZnPg==", style: "width 64px; height 64px;" }/
      .media-body
        %h4#top-aligned-media.media-heading
          Top aligned media
          %span.label.label-default.project-number
            29
            %i Projects
        .proto-user
          %span.degree we-b inc. Designer
        .row
          .col-md-6
            %h4 Profile
            %p Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
          .col-md-6
            %h4 Works
            %p Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
.container.proto-list
  .row
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{ href: "" }
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                %a{ href: "#", class: "btn btn-default" } iPad
              %li 
                %a{ href: "#", class: "btn btn-default" } wireframe
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{ href: "" }
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                %a{ href: "#", class: "btn btn-default" } iPad
              %li 
                %a{ href: "#", class: "btn btn-default" } wireframe
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{ href: "" }
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                %a{ href: "#", class: "btn btn-default" } iPad
              %li 
                %a{ href: "#", class: "btn btn-default" } wireframe
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{ href: "" }
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                %a{ href: "#", class: "btn btn-default" } iPad
              %li 
                %a{ href: "#", class: "btn btn-default" } wireframe
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{ href: "" }
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                %a{ href: "#", class: "btn btn-default" } iPad
              %li 
                %a{ href: "#", class: "btn btn-default" } wireframe
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{ href: "" }
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                %a{ href: "#", class: "btn btn-default" } iPad
              %li 
                %a{ href: "#", class: "btn btn-default" } wireframe
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{ href: "" }
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                %a{ href: "#", class: "btn btn-default" } iPad
              %li 
                %a{ href: "#", class: "btn btn-default" } wireframe
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{ href: "" }
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                %a{ href: "#", class: "btn btn-default" } iPad
              %li 
                %a{ href: "#", class: "btn btn-default" } wireframe
                
.text-center
  %ul.pagination
    %li.disabled
      %a{ "aria-label": "Previous", href: "#" }
        %span{ "aria-hidden": "true" } «
    %li.active
      %a{ href: "#" }
        1
        %span.sr-only (current)
    %li
      %a{ href: "#" } 2
    %li
      %a{ href: "#" } 3
    %li
      %a{ href: "#" } 4
    %li
      %a{ href: "#" } 5
    %li
      %a{ "aria-label": "Next", href: "#" }
        %span{ "aria-hidden": "true" } »

app/views/users/new.html.haml
%form.container.user-new{ action: "" }
  .col-md-8.col-md-offset-2
    %header.row.user-nav.row
      .col-md-12
        %h2 Register
        .user-name_image.row
          .user-name.col-md-10
            %input{ type: "text", placeholder: "Username" }/
          .user-image.col-md-2
            %button.btn.btn-primary Add image
            %input{ type: "file" }/
        %input.user-email{ type: "email", placeholder: "E-Mail" }/
        %input.user-password{ type: "password", placeholder: "Password" }/
      .col-md-12
        %h4 Member of
        .user-user-member.row
          .user-name.col-md-12
            %input{ type: "text", placeholder: "Member" }/
        %h4 Profile
        .user-user-profile.row
          .user-name.col-md-12
            %textarea{ name: "textarea", cols: "30", rows: "4", placeholder: "Profile" }
        %h4 Works 
        .user-name_image.row
          .user-name.col-md-12
            %textarea{ name: "textarea", cols: "30", rows: "4", placeholder: "Works" }
    .row.text-center.user-btn
      %button.btn.btn-lg.btn-primary.btn-block{ type: "submit" } Save
      

app/views/users/show.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-left
        = image_tag current_user.avatar, width: 64, height: 64
      .media-body
        %h4#top-aligned-media.media-heading
          = current_user.name
          %span.label.label-default.project-number
            = current_user.prototypes.count
            %i Dishes

.container.proto-list
  .row
    = render partial: 'prototypes/prototype'